#!/usr/bin/env bash
# displaying good luck, best school, and bad luck
cont=0
while [ $cont -lt 10 ];
do
	if [ $cont -eq 3 ]
	then
echo "bad luck"
	elif [ $cont -eq 7 ]
	then
echo "good luck"
	else
echo "Best School"
	fi
	(( cont = cont +1 ))
done
