#!/usr/bin/env bash
# bad luck from china on 4th 
#bad luck from japan on 9th
#bad luck from italy on 17th
counter=1
while [ $counter -lt 21 ];
	do
		echo $counter
		case "$counter" in
			"4")
			echo "bad luck from China"
			;;
			"9")
			echo "bad luck from Japan"
			;;
			"17")
			echo "bad luck from Italy"
			;;
	esac
	(( counter = counter +1 ))
done
