#!/usr/bin/env bash
# bad luck from china on 4th, bad luck from japan on 9th, bad luck from italy on 17th

Counter=1
while [ "$Counter" -le 20 ];
	do
	echo "$Counter"
	case "$Counter" in
4)
	echo "bad luck from China'
	;;
9)
	echo "bad luck from Japan"
	;;
17)
	echo "bad luck from Italy"
	;;
	esac
	(( Counter = Counter +1 ))
done
