#!/usr/bin/env bash
#bash script displaying the time for 12 hours and 59 minutes
hour=0
while [ $hours -le 12 ];
do
	echo "Hour: $Hour"
	minutes=1
	while [ $minutes -le 59 ];
	do
echo $minutes
(( minutes = minutes +1 ))
